development:
  adapter: postgresql
  encoding: unicode
  database: daywon-api_development
  pool: 10
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: daywon-api_test
  pool: 10
  password: root

staging:
  adapter: postgresql
  encoding: unicode
  database: daywon-api_staging
  pool: 10
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: daywon-api_production
  pool: 10
  password:

