development:
  adapter: postgresql
  encoding: unicode
  database: tent_development
  pool: 10
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: tent_test
  pool: 10
  password: root

staging:
  adapter: postgresql
  encoding: unicode
  database: tent_staging
  pool: 10
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tent_production
  pool: 10
  password:

